#!/usr/bin/env php
<?php

require __DIR__ . "/bootstrap/app.php";

/** @var Phinx\Console\PhinxApplication $app */
$app = require __DIR__ . '/vendor/robmorgan/phinx/app/phinx.php';

/** @noinspection PhpUnhandledExceptionInspection */
$app->run();
